"use client";

import { useEffect, useState } from "react";
import Link from "next/link";
import { ArrowRight, CheckCircle2, FileUp, GraduationCap, LoaderCircle } from "lucide-react";
import { createClient } from "@/lib/supabase/client";
import { uploadFile } from "@/app/actions/files";

const contentTypes = [{ value: "lecture", label: "محاضرة" }, { value: "summary", label: "ملخص" }, { value: "questions", label: "أسئلة" }, { value: "audio_lecture", label: "محاضرة صوتية" }, { value: "other", label: "ملف آخر" }];
export default function UploadPage() {
  const [data, setData] = useState({ stages: [], semesters: [], subjects: [], years: [], batches: [] }); const [loading, setLoading] = useState(true); const [sending, setSending] = useState(false); const [result, setResult] = useState("");
  useEffect(() => { const supabase = createClient(); supabase.auth.getUser().then(async ({ data: auth }) => { if (!auth.user) { window.location.assign("/login"); return; } const [stages, semesters, subjects, years, batches] = await Promise.all([supabase.from("stages").select("id,name").order("sort_order"), supabase.from("semesters").select("id,name,stage_id").order("sort_order"), supabase.from("subjects").select("id,name,stage_id,semester_id").order("name"), supabase.from("academic_years").select("id,name").order("starts_on", { ascending: false }), supabase.from("batches").select("id,name").order("name")]); setData({ stages: stages.data || [], semesters: semesters.data || [], subjects: subjects.data || [], years: years.data || [], batches: batches.data || [] }); setLoading(false); }); }, []);
  const submit = async (e) => { e.preventDefault(); const form = e.currentTarget; setSending(true); setResult(""); try { const response = await uploadFile(new FormData(form)); setResult(response?.error || response?.success || "لم تصل استجابة من الخادم."); if (response?.success) form.reset(); } catch (error) { console.error("Upload failed:", error); setResult(`تعذر إرسال الملف: ${error?.message || "خطأ غير متوقع"}`); } finally { setSending(false); } };
  if (loading) return <main className="upload-page center-state"><LoaderCircle className="spin"/> جارٍ تجهيز نموذج الرفع...</main>;
  const noTaxonomy = !data.stages.length || !data.semesters.length || !data.subjects.length || !data.years.length;
  return <main className="upload-page"><header className="upload-header"><Link className="brand" href="/"><span className="brand-mark"><GraduationCap size={23}/></span><span>مكتبة <b>القسم</b></span></Link><Link href="/" className="back-home"><ArrowRight size={17}/> العودة للمكتبة</Link></header><section className="upload-card"><div className="upload-title"><span><FileUp/></span><div><h1>رفع محتوى دراسي</h1><p>سيتم إرسال الملف إلى الإدارة للمراجعة قبل نشره.</p></div></div>{noTaxonomy ? <div className="setup-warning"><h3>يلزم إدخال البيانات الأكاديمية أولًا</h3><p>أضف مرحلة وفصلًا ومادة وسنة دراسية من Supabase SQL Editor قبل رفع أول ملف.</p></div> : <form onSubmit={submit} className="upload-form"><label>عنوان الملف<input name="title" required maxLength="180" placeholder="مثال: المحاضرة الأولى — مدخل إلى الذكاء الاصطناعي" /></label><div className="form-grid"><label>المرحلة<select name="stage_id" required defaultValue=""><option value="" disabled>اختر المرحلة</option>{data.stages.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الفصل<select name="semester_id" required defaultValue=""><option value="" disabled>اختر الفصل</option>{data.semesters.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>المادة<select name="subject_id" required defaultValue=""><option value="" disabled>اختر المادة</option>{data.subjects.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>السنة الدراسية<select name="academic_year_id" required defaultValue=""><option value="" disabled>اختر السنة</option>{data.years.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>الدفعة <small>اختياري</small><select name="batch_id" defaultValue=""><option value="">بدون تحديد</option>{data.batches.map(x => <option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>نوع المحتوى<select name="content_type" required defaultValue=""><option value="" disabled>اختر النوع</option>{contentTypes.map(x => <option key={x.value} value={x.value}>{x.label}</option>)}</select></label></div><label className="file-picker">اختر الملف<input name="file" type="file" required accept=".pdf,.doc,.docx,.ppt,.pptx,.zip,.mp3,.wav,.ogg,.m4a,.png,.jpg,.jpeg" /><small>PDF، Word، PowerPoint، ZIP، صوتيات وصور — الحد الأقصى 50MB</small></label>{result && <p className={result.startsWith("تم") ? "auth-success" : "auth-error"}>{result}</p>}<button className="auth-submit" disabled={sending}>{sending && <LoaderCircle className="spin" size={19}/>}إرسال للمراجعة</button></form>}</section></main>;
}
