create extension if not exists pgcrypto;
do $$ begin create type public.user_role as enum ('student','admin','moderator'); exception when duplicate_object then null; end $$;
do $$ begin create type public.file_status as enum ('pending','approved','rejected'); exception when duplicate_object then null; end $$;
do $$ begin create type public.content_kind as enum ('lecture','summary','questions','audio_lecture','other'); exception when duplicate_object then null; end $$;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, role public.user_role not null default 'student', created_at timestamptz not null default now());
create table public.stages (id uuid primary key default gen_random_uuid(), name text not null unique, sort_order smallint not null default 0, created_at timestamptz not null default now());
create table public.semesters (id uuid primary key default gen_random_uuid(), stage_id uuid not null references public.stages(id) on delete cascade, name text not null, sort_order smallint not null default 0, unique(stage_id,name));
create table public.subjects (id uuid primary key default gen_random_uuid(), stage_id uuid not null references public.stages(id) on delete cascade, semester_id uuid not null references public.semesters(id) on delete cascade, name text not null, code text, unique(semester_id,name));
create table public.academic_years (id uuid primary key default gen_random_uuid(), name text not null unique, starts_on date, ends_on date, is_current boolean not null default false);
create table public.batches (id uuid primary key default gen_random_uuid(), name text not null unique, graduation_year smallint);
create table public.files (id uuid primary key default gen_random_uuid(), title text not null check (char_length(title) <= 180), original_name text not null, storage_path text not null unique, mime_type text not null, size_bytes bigint not null check (size_bytes > 0 and size_bytes <= 52428800), content_type public.content_kind not null, stage_id uuid not null references public.stages(id), semester_id uuid not null references public.semesters(id), subject_id uuid not null references public.subjects(id), academic_year_id uuid not null references public.academic_years(id), batch_id uuid references public.batches(id), uploader_id uuid not null references public.profiles(id), status public.file_status not null default 'pending', rejection_reason text, reviewer_id uuid references public.profiles(id), reviewed_at timestamptz, published_at timestamptz, created_at timestamptz not null default now());
create table public.file_reviews (id uuid primary key default gen_random_uuid(), file_id uuid not null references public.files(id) on delete cascade, reviewer_id uuid not null references public.profiles(id), status public.file_status not null, reason text, created_at timestamptz not null default now());
create table public.downloads (id uuid primary key default gen_random_uuid(), file_id uuid not null references public.files(id) on delete cascade, profile_id uuid references public.profiles(id), downloaded_at timestamptz not null default now());
create table public.notifications (id uuid primary key default gen_random_uuid(), profile_id uuid not null references public.profiles(id) on delete cascade, title text not null, body text, read_at timestamptz, created_at timestamptz not null default now());
create table public.activity_logs (id bigint generated always as identity primary key, actor_id uuid references public.profiles(id), action text not null, entity_type text not null, entity_id uuid, metadata jsonb not null default '{}', created_at timestamptz not null default now());
create index files_lookup_idx on public.files(stage_id,semester_id,subject_id,academic_year_id,batch_id,status,created_at desc);
create index files_search_idx on public.files using gin (to_tsvector('arabic', title));
create index downloads_file_idx on public.downloads(file_id,downloaded_at desc);

create or replace function public.is_staff() returns boolean language sql stable security definer set search_path=public as $$select exists(select 1 from public.profiles where id=auth.uid() and role in ('admin','moderator'))$$;
create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$begin insert into public.profiles(id,full_name) values(new.id,coalesce(new.raw_user_meta_data->>'full_name','')); return new; end;$$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
alter table public.profiles enable row level security; alter table public.stages enable row level security; alter table public.semesters enable row level security; alter table public.subjects enable row level security; alter table public.academic_years enable row level security; alter table public.batches enable row level security; alter table public.files enable row level security; alter table public.file_reviews enable row level security; alter table public.downloads enable row level security; alter table public.notifications enable row level security; alter table public.activity_logs enable row level security;
create policy "public reads taxonomy" on public.stages for select using(true); create policy "public reads semesters" on public.semesters for select using(true); create policy "public reads subjects" on public.subjects for select using(true); create policy "public reads years" on public.academic_years for select using(true); create policy "public reads batches" on public.batches for select using(true);
create policy "profiles self read" on public.profiles for select using(id=auth.uid() or public.is_staff()); create policy "approved files public read" on public.files for select using(status='approved' or uploader_id=auth.uid() or public.is_staff()); create policy "student creates own files" on public.files for insert with check(uploader_id=auth.uid() and status='pending'); create policy "student updates pending own" on public.files for update using(uploader_id=auth.uid() and status='pending') with check(uploader_id=auth.uid() and status='pending'); create policy "staff manages files" on public.files for all using(public.is_staff()) with check(public.is_staff()); create policy "owner reads notifications" on public.notifications for select using(profile_id=auth.uid()); create policy "staff logs" on public.activity_logs for select using(public.is_staff());
insert into storage.buckets (id,name,public,file_size_limit,allowed_mime_types) values ('study-files','study-files',false,52428800,array['application/pdf','application/msword','application/vnd.openxmlformats-officedocument.wordprocessingml.document','application/vnd.ms-powerpoint','application/vnd.openxmlformats-officedocument.presentationml.presentation','application/zip','audio/mpeg','audio/wav','audio/ogg','audio/mp4','image/png','image/jpeg']) on conflict(id) do nothing;
create policy "authenticated upload own folder" on storage.objects for insert to authenticated with check(bucket_id='study-files' and (storage.foldername(name))[1]=auth.uid()::text); create policy "public gets approved through signed urls only" on storage.objects for select to authenticated using(bucket_id='study-files' and owner_id=auth.uid()::text);
